Repository Cheers-Project/Cheers-Front, pull requests merged in 2022-05, with the labels that each got.

#190 헤더 UI 수정
  src/components/common/Header.jsx
Labels: style

#191 변경 사항 메인 브렌치로 병합
  src/components/common/Header.jsx
Labels: style

#192 .env 수정
  README.md
Labels: config

#200 게시물 댓글 UI, 버그 수정
  src/components/board/BoardEditor.jsx
  src/components/board/BoardList.jsx
  src/components/board/Pagination.jsx
  src/components/comment/CommentUpdater.jsx
  src/components/comment/CommentWriter.jsx
Labels: fix

#202 변수명 수정
  src/api/meeting.js
Labels: refactor

#204 모임 관련 버그 수정
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingLocation.jsx
  src/components/meeting/MeetingMap.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MeetingTime.jsx
  src/hooks/useCurrentLocation.js
Labels: fix

#205 문제 해결 후 메인 브랜치로 병합
  src/api/meeting.js
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingLocation.jsx
  src/components/meeting/MeetingMap.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MeetingTime.jsx
  src/hooks/useCurrentLocation.js
Labels: fix

#206 모임 생성 컴포넌트 일부 수정
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingTime.jsx
Labels: fix, refactor

#207 모임 생성 수정 사항 병합
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingTime.jsx
Labels: fix, refactor

#208 모임 지도 위치 서비스 관련 문제 수정
  src/components/meeting/MeetingMap.jsx
Labels: fix

#209 모임 지도 관련 문제 수정 후 병합
  src/components/meeting/MeetingMap.jsx
Labels: fix

#211 모임 관련 문제 수정
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingWriteButton.jsx
Labels: fix

#213 모임 관련 문제 수정 및 삭제 알람 구현
  src/components/meeting/DeleteMeetingAlarm.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingWriteButton.jsx
Labels: fix, feature

#214 모임 관련 문제 수정 및 삭제 확인 알람 구현 후 병합
  src/components/meeting/DeleteMeetingAlarm.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingWriteButton.jsx
Labels: fix, feature

#216 비밀번호 입력창 문제 수정
  src/components/user/RegistForm.jsx
Labels: fix

#217 수정 사항 메인 브랜치로 병합
  src/components/user/RegistForm.jsx
Labels: fix

#219 게시물 리스트 페이지네이션 수정
  README.md
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/Pagination.jsx
Labels: fix

#224 댓글수 감소 문제 수정, 스타일 수정
  src/api/comment.js
  src/components/board/BoardItem.jsx
  src/components/comment/CommentItem.jsx
  src/components/common/Header.jsx
Labels: fix, style

#226 유저 닉네임 깨지는 문제 수정
  src/components/meeting/MeetingItem.jsx
Labels: fix

#227 변경사항 병합
  src/components/meeting/MeetingItem.jsx
Labels: fix

#230 게시물 작성 이미지 업로드 문제 수정
  src/components/board/BoardEditor.jsx
Labels: fix

#232 마감된 모임에 대한 알림 텍스트 구현
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingItem.jsx
Labels: feature, style

#235 아이디, 닉네임 중복에 대한 예외처리 구현
  src/components/user/RegistForm.jsx
Labels: feature

#237 푸터 텍스트 및 깃헙 링크 변경
  src/components/common/Footer.jsx
Labels: refactor

#238 메인 브랜치로 변경사항 병합
  src/components/common/Footer.jsx
Labels: refactor

#240 모임 페이지 이동 시 재 요청 리팩토링
  src/components/meeting/MeetingList.jsx
Labels: refactor

#241 변경 사항 메인 브랜치로 병합
  src/components/meeting/MeetingList.jsx
Labels: refactor

#243 페이지네이션 버그 수정, 설정 수정
  package-lock.json
  package.json
  src/components/board/BoardList.jsx
  src/components/board/Pagination.jsx
Labels: fix

#246 모임 생성 시 오늘 날짜 선택 표시 되어있는 문제 수정
  src/components/meeting/MeetingCalendar.jsx
Labels: fix

#247 변경사항 메인 브랜치로 병합
  src/components/meeting/MeetingCalendar.jsx
Labels: fix

#248 모임 리스트 레이아웃 간격 조정
  src/components/meeting/MeetingList.jsx
Labels: style

#249 변경사항 메인 브랜치로 병합
  src/components/meeting/MeetingList.jsx
Labels: style

#250 모임 제목 레이아웃 수정
  src/components/meeting/MeetingItem.jsx
Labels: style

#251 변경 사항 메인 브랜치로 병합
  src/components/meeting/MeetingItem.jsx
Labels: style
