Repository Cheers-Project/Cheers-Front, pull requests merged in 2022-03, with the labels that each got.

#4 [로그인] UI, 기능 구현
  .gitignore
  .nvmrc
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/common/LoginModal.jsx
  src/components/common/Modal.jsx
  src/components/common/ModalWrapper.jsx
  src/hooks/useModal.js
  src/pages/MainPage.jsx
  src/styles/GlobalStyles.jsx
Labels: feature, style

#5 [회원가입] UI 구현
  package-lock.json
  package.json
  src/App.js
  src/components/regist/Avatar.jsx
  src/components/regist/RegistForm.jsx
  src/components/regist/RegistTemplate.jsx
  src/pages/RegistPage.jsx
  src/styles/GlobalStyles.jsx
Labels: style

#9 [회원가입] 유저 프로필 기능 구현
  src/App.js
  src/components/regist/Avatar.jsx
Labels: feature

#13 유저 공통 레이아웃 구현
  src/components/common/Responsive.jsx
  src/components/common/UserTemplate.jsx
  src/components/regist/Avatar.jsx
  src/components/regist/RegistForm.jsx
  src/components/regist/RegistTemplate.jsx
  src/index.js
  src/pages/RegistPage.jsx
Labels: style

#14 공통 헤더, 푸터 UI 구현
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/Menu.jsx
  src/components/common/MenuList.jsx
  src/pages/MainPage.jsx
  src/styles/GlobalStyles.jsx
Labels: style

#15 헤더 푸터 UI 구현
  src/components/common/Header.jsx
  src/index.js
  src/pages/MainPage.jsx
Labels: style

#16 회원가입 기능 구현
  package-lock.json
  package.json
  src/components/common/StyledInput.jsx
  src/components/regist/Avatar.jsx
  src/components/regist/RegistForm.jsx
  src/pages/RegistPage.jsx
  src/utils/validation/registSchema.js
Labels: feature, style

#19 유저 프로필 이미지 기능 구현
  src/components/common/Responsive.jsx
  src/components/regist/Avatar.jsx
  src/components/regist/RegistForm.jsx
Labels: feature

#21 프로필 이미지 변수명 수정
  src/components/regist/Avatar.jsx
  src/components/regist/RegistForm.jsx
  src/utils/validation/registSchema.js
Labels: refactor

#26 로그인 모달 수정
  src/assets/images/ico_kakao.png
  src/components/common/Header.jsx
  src/components/login/LoginModal.jsx
  src/pages/MainPage.jsx
  src/utils/validation/loginSchema.js
Labels: feature, style

#27 메인 페이지 배너 UI 구현
  src/components/common/Header.jsx
  src/components/common/Responsive.jsx
  src/components/main/Banner.jsx
  src/pages/MainPage.jsx
Labels: style

#28 메인 페이지 모임 영역 UI 구현
  package-lock.json
  package.json
  src/assets/images/banner.jpg
  src/components/main/Banner.jsx
  src/components/main/MainContent.jsx
  src/components/main/MeetSlider.jsx
  src/pages/MainPage.jsx
Labels: style

#29 카카오 로그인
  src/pages/KakaoPage.jsx
Labels: feature

#32 메인 페이지 UI 구현
  src/assets/images/board-banner.jpeg
  src/assets/images/meet-banner.jpg
  src/components/main/MainContent.jsx
  src/components/main/MeetSlider.jsx
Labels: style

#34 근처 모임 요청 기능 구현
  src/pages/MainPage.jsx
  src/pages/RedirectPage.jsx
Labels: feature

#36 헤더 수정
  package.json
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/common/ModalWrapper.jsx
Labels: feature

#37 컴포넌트 이름 수정 및 디렉토리 위치 변경
  src/components/regist/RegistTemplate.jsx
  src/pages/RegistPage.jsx
Labels: refactor

#41 로그인 회원 전역 상태 관리
  package-lock.json
  package.json
  src/api/index.js
  src/api/user.js
  src/components/common/Header.jsx
  src/components/common/Menu.jsx
  src/components/login/LoginForm.jsx
  src/components/login/LoginModal.jsx
  src/components/regist/RegistForm.jsx
  src/index.js
  src/redux/configStore.js
  src/redux/modules/user.js
  src/sagas/userSaga.js
Labels: feature

#43 카카오 로그인 회원 전역 상태 관리
  src/api/meet.js
  src/api/user.js
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/login/LoginForm.jsx
  src/components/login/LoginModal.jsx
  src/components/regist/RegistForm.jsx
  src/hooks/useModal.js
  src/pages/KakaoPage.jsx
  src/pages/MainPage.jsx
  src/pages/RedirectPage.jsx
  src/redux/modules/user.js
  src/sagas/userSaga.js
Labels: refactor

#46 로그아웃 구현
  src/api/index.js
  src/api/user.js
  src/components/common/MenuList.jsx
  src/components/login/LoginModal.jsx
  src/pages/KakaoPage.jsx
  src/pages/RedirectPage.jsx
  src/redux/modules/user.js
  src/sagas/userSaga.js
Labels: feature

#47 로그인, 회원가입 모달 리팩토링
  src/App.js
  src/components/common/MenuList.jsx
  src/components/login/LoginModal.jsx
  src/components/regist/RegistForm.jsx
  src/components/regist/RegistTemplate.jsx
  src/components/user/Avatar.jsx
  src/components/user/LoginForm.jsx
  src/components/user/RegistForm.jsx
  src/components/user/UserModal.jsx
  src/hooks/useModal.js
  src/pages/RegistPage.jsx
Labels: refactor, style

#50 모달 전역 상태 관리, 카카오 페이지 컴포넌트화
  src/api/index.js
  src/api/user.js
  src/components/auth/KakaoLogin.jsx
  src/components/auth/KakaoRedirect.jsx
  src/components/auth/Spinner.jsx
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/common/ModalWrapper.jsx
  src/components/user/LoginForm.jsx
  src/components/user/RegistForm.jsx
  src/components/user/UserModal.jsx
  src/pages/KakaoPage.jsx
  src/pages/RedirectPage.jsx
  src/redux/configStore.js
  src/redux/modules/modal.js
Labels: refactor, feature

#51 마이 페이지 일부 구현
  src/App.js
  src/components/common/Footer.jsx
  src/components/common/Spacer.jsx
  src/components/my/MyBoard.jsx
  src/components/my/MyInfo.jsx
  src/components/my/MyMeeting.jsx
  src/components/my/SubMenu.jsx
  src/components/user/Avatar.jsx
  src/components/user/LoginForm.jsx
  src/components/user/RegistForm.jsx
  src/components/user/UserModal.jsx
  src/pages/MyPage.jsx
Labels: feature, style

#54 로그인 비동기 로직 리팩토링
  package-lock.json
  package.json
  src/api/user.js
  src/components/auth/KakaoLogin.jsx
  src/components/auth/KakaoRedirect.jsx
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/user/LoginForm.jsx
  src/index.js
  src/redux/modules/user.js
  src/sagas/userSaga.js
Labels: refactor

#55 로그인 비동기 로직 리팩토링
  src/api/user.js
  src/components/auth/KakaoLogin.jsx
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/user/LoginForm.jsx
  src/components/user/RegistForm.jsx
  src/pages/MainPage.jsx
Labels: refactor

#56 메인 페이지에서 유저 정보 요청하도록 리팩토링
  src/api/user.js
  src/components/auth/KakaoLogin.jsx
  src/components/common/MenuList.jsx
  src/components/user/LoginForm.jsx
  src/pages/MainPage.jsx
Labels: refactor

#59 헤더, 로그인 로직 수정
  package-lock.json
  package.json
  src/api/user.js
  src/components/auth/KakaoLogin.jsx
  src/components/auth/KakaoRedirect.jsx
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/user/LoginForm.jsx
  src/hooks/useModal.js
  src/redux/configStore.js
  src/redux/modules/user.js
  src/sagas/userSaga.js
Labels: feature, style

#60 카카오 로그인 서버 상태 관리 변경
  src/components/auth/KakaoLogin.jsx
Labels: refactor

#61 회원가입 로직 리팩토링
  src/api/user.js
  src/components/my/Avatar.jsx
  src/components/my/MyInfo.jsx
  src/components/user/RegistForm.jsx
  src/pages/MainPage.jsx
Labels: refactor

#63 유저 프로필 이미지 수정 및 제거 기능 구현
  src/api/user.js
  src/components/my/Avatar.jsx
  src/components/my/MyInfo.jsx
Labels: feature
