Repository Cheers-Project/Cheers-Front, pull requests merged in 2022-04, with the labels that each got.

#64 내 정보 페이지 구현
  src/api/user.js
  src/components/auth/KakaoLogin.jsx
  src/components/common/ErrorMessage.jsx
  src/components/my/Avatar.jsx
  src/components/my/InfoTemplate.jsx
  src/components/my/MyInfo.jsx
  src/components/my/NicknameForm.jsx
  src/components/my/SubMenu.jsx
  src/components/user/LoginForm.jsx
  src/components/user/RegistForm.jsx
  src/utils/validation/nicknameSchema.js
Labels: refactor, feature

#66 게시물 작성 기능 구현
  package-lock.json
  package.json
  src/App.js
  src/api/board.js
  src/components/board/BoardEditor.jsx
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/pages/BoardWritePage.jsx
  src/styles/GlobalStyles.jsx
Labels: feature

#68 유저 정보 수정 로직 일부 리팩토링
  src/components/my/NicknameForm.jsx
Labels: refactor

#70 공통 테마 설정
  src/components/common/Header.jsx
  src/components/common/StyledButton.jsx
  src/components/my/Avatar.jsx
  src/index.js
  src/styles/theme.js
Labels: feature, style

#72 모임 작성 페이지 UI 구현
  package-lock.json
  package.json
  src/App.js
  src/components/common/Outer.jsx
  src/components/common/Responsive.jsx
  src/components/common/Spacer.jsx
  src/components/main/MeetSlider.jsx
  src/components/meeting/MeetingCalendar.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingEditor.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingLocation.jsx
  src/components/meeting/MeetingOption.jsx
  src/components/meeting/MeetingTemplate.jsx
  src/components/meeting/MemberCounter.jsx
  src/components/meeting/SearchMap.jsx
  src/hooks/useCount.js
  src/pages/MeetingDetailPage.jsx
  src/pages/MeetingPage.jsx
  src/pages/MeetingWritePage.jsx
  src/styles/GlobalStyles.jsx
Labels: style

#73 게시물 리스트 페이지 수정
  package.json
  src/App.js
  src/api/board.js
  src/components/board/BoardEditor.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/Pagination.jsx
  src/components/common/Header.jsx
  src/components/my/Avatar.jsx
  src/components/my/NicknameForm.jsx
  src/pages/BoardListPage.jsx
  src/pages/BoardWritePage.jsx
  src/styles/theme.js
Labels: feature, style

#77 게시물 리스트 UI 수정, 기능 추가
  src/api/board.js
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/Pagination.jsx
Labels: feature, style

#80 모임 작성 상태관리 및 최신 모임 요청 구현
  src/api/meet.js
  src/api/meeting.js
  src/components/main/MainContent.jsx
  src/components/main/MeetingItem.jsx
  src/components/main/MeetingSlider.jsx
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingCalendar.jsx
  src/components/meeting/MeetingMap.jsx
  src/components/meeting/MeetingTime.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/hooks/useCount.js
  src/hooks/useCurrentLocation.js
  src/pages/MainPage.jsx
  src/redux/configStore.js
  src/redux/modules/meeting.js
Labels: feature

#83 게시물 리스트 페이지네이션 구현, 게시물 상세페이지 API 구현
  src/App.js
  src/api/board.js
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/Pagination.jsx
  src/components/common/Header.jsx
  src/pages/BoardDetailPage.jsx
  src/pages/BoardWritePage.jsx
Labels: feature

#86 게시물 상세페이지 UI, 게시물 조회수 증가 API
  src/api/board.js
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/DateInfo.jsx
  src/components/board/Pagination.jsx
  src/components/board/UserInfo.jsx
Labels: refactor, feature, style

#88 마이페이지 내 모임 요청 및 UI 구현
  src/App.js
  src/api/my.js
  src/api/user.js
  src/components/common/Header.jsx
  src/components/my/Avatar.jsx
  src/components/my/MyMeeting.jsx
  src/components/my/NicknameForm.jsx
  src/components/my/SubMenu.jsx
  src/styles/GlobalStyles.jsx
Labels: refactor, feature, style

#93 모임 리스트 페이지 UI 구현
  package-lock.json
  package.json
  src/components/common/StyledButton.jsx
  src/components/main/MainContent.jsx
  src/components/main/MeetingItem.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/components/meeting/WriteTemplate.jsx
  src/components/my/MyMeeting.jsx
  src/components/my/NicknameForm.jsx
  src/components/my/SubMenu.jsx
  src/pages/MeetingPage.jsx
  src/pages/MeetingWritePage.jsx
Labels: style

#98 게시물 조회 서버 상태 관리
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/Pagination.jsx
  src/components/common/Header.jsx
  src/hooks/useCheckOwned.js
  src/pages/BoardWritePage.jsx
Labels: feature

#99 게시물 삭제 구현
  src/api/board.js
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardItem.jsx
  src/components/board/DeleteBtn.jsx
  src/hooks/useCheckOwned.js
Labels: feature

#100 모임 API 무한 스크롤 요청 구현
  src/api/meeting.js
  src/components/meeting/MeetingList.jsx
  src/hooks/useInterSectionObserver.js
Labels: feature

#101 NotFoundPage 생성
  src/App.js
  src/pages/NotFoundPage.jsx
Labels: feature

#103 게시물 요청 수정
  src/api/board.js
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/Pagination.jsx
Labels: refactor

#106 위치 서비스 권한 처리
  src/components/common/Header.jsx
  src/components/common/StyledButton.jsx
  src/components/main/MainContent.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/hooks/useCurrentLocation.js
  src/redux/modules/modal.js
Labels: refactor, feature

#108 모임 조회수 증가 구현
  src/api/meeting.js
  src/components/main/MeetingItem.jsx
  src/components/main/MeetingSlider.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingItem.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/my/MyMeeting.jsx
  src/hooks/useCurrentQuery.js
  src/hooks/useViewQuery.js
  src/pages/MeetingDetailPage.jsx
Labels: feature

#111 내가 작성한 게시물 불러오기 구현
  src/api/my.js
  src/components/meeting/MeetingList.jsx
  src/components/my/MyBoard.jsx
  src/components/my/MyMeeting.jsx
Labels: feature

#112 조회수 증가 훅으로 관리
  src/components/board/BoardDetail.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/DeleteBtn.jsx
  src/components/board/LikeBtn.jsx
  src/components/board/Pagination.jsx
  src/components/board/UserInfo.jsx
  src/hooks/useLikeQuery.js
  src/hooks/useOwnedQuery.js
Labels: refactor, style

#115 모임 조회수 증가 API 수정
  src/api/meeting.js
  src/components/main/MeetingSlider.jsx
  src/components/meeting/MeetingItem.jsx
  src/components/meeting/MeetingList.jsx
  src/components/my/MyMeeting.jsx
  src/hooks/useViewQuery.js
Labels: refactor

#116 게시물 조회수 증가 수정
  src/api/board.js
  src/components/board/BoardDetail.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardNav.jsx
  src/components/common/Header.jsx
  src/components/meeting/MeetingNav.jsx
Labels: refactor, style

#119 모임 수정 구현
  src/App.js
  src/api/meeting.js
  src/components/common/MenuList.jsx
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingCalendar.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingList.jsx
  src/components/meeting/MeetingLocation.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MeetingTime.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/components/meeting/MemberCounter.jsx
  src/hooks/useCount.js
  src/hooks/useMeetingQuery.js
  src/redux/modules/meeting.js
Labels: feature

#120 게시물 수정 구현
  src/App.js
  src/api/board.js
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardViewer.jsx
  src/hooks/useBoardQuery.js
Labels: refactor

#122 모임 쿼리 수정
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/components/my/MyBoard.jsx
  src/hooks/useMeetingQuery.js
  src/hooks/useOwnedQuery.js
Labels: refactor, feature

#123 모임 삭제 구현
  src/api/meeting.js
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingWriteButton.jsx
Labels: feature

#124 게시물 조회 수정 서버 상태 옵션 수정
  src/components/board/BoardEditor.jsx
  src/hooks/useBoardQuery.js
Labels: refactor

#126 헤더 라우팅 수정
  src/components/common/Header.jsx
Labels: refactor

#128 댓글 작성 구현
  src/api/comment.js
  src/components/board/BoardDetail.jsx
  src/components/comment/CommentWriter.jsx
Labels: feature

#132 댓글 요청 구현
  src/api/comment.js
  src/components/board/BoardDetail.jsx
  src/components/comment/CommentList.jsx
  src/components/comment/CommentWriter.jsx
  src/hooks/useCommentQuery.js
Labels: feature

#133 댓글 삭제 구현 실시간 반영 구현
  src/api/comment.js
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentList.jsx
  src/components/comment/CommentWriter.jsx
  src/hooks/useCommentQuery.js
Labels: feature

#138 게시물 상세페이지 UI
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/DeleteBtn.jsx
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentList.jsx
  src/components/comment/CommentUpdater.jsx
  src/components/comment/CommentWriter.jsx
  src/components/common/Header.jsx
  src/pages/BoardDetailPage.jsx
Labels: style

#139 마이 페이지 UI 추가 구현
  src/components/common/Outer.jsx
  src/components/common/StyledButton.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/my/MyBoard.jsx
  src/components/my/MyMeeting.jsx
  src/pages/MyPage.jsx
  src/styles/GlobalStyles.jsx
Labels: feature, style

#140 게시물 수정 구현
  src/api/comment.js
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentUpdater.jsx
Labels: feature

#144 모임 상세정보 페이지 수정
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingMap.jsx
Labels: feature, style

#146 함수명 리팩토링
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/common/ModalWrapper.jsx
  src/components/common/StyledButton.jsx
  src/components/main/MeetingSlider.jsx
  src/components/meeting/LeftEditor.jsx
  src/components/meeting/MeetingCalendar.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingItem.jsx
  src/components/meeting/MeetingLocation.jsx
  src/components/meeting/MeetingMap.jsx
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MeetingTime.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/components/meeting/MemberCounter.jsx
  src/components/my/Avatar.jsx
  src/components/my/MyBoard.jsx
  src/components/my/MyInfo.jsx
  src/components/my/MyMeeting.jsx
  src/components/my/NicknameForm.jsx
  src/components/user/LoginForm.jsx
  src/components/user/RegistForm.jsx
  src/components/user/UserModal.jsx
Labels: refactor

#147 함수명 리팩토링
  src/api/comment.js
  src/components/auth/KakaoLogin.jsx
  src/components/auth/KakaoRedirect.jsx
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardList.jsx
  src/components/board/BoardNav.jsx
  src/components/board/BoardViewer.jsx
  src/components/board/DeleteBtn.jsx
  src/components/board/LikeBtn.jsx
  src/components/board/Pagination.jsx
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentList.jsx
  src/components/comment/CommentUpdater.jsx
  src/components/comment/CommentWriter.jsx
  src/styles/GlobalStyles.jsx
Labels: refactor

#149 폰트 사이즈 통일
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/MenuList.jsx
  src/components/common/StyledButton.jsx
  src/components/main/Banner.jsx
  src/components/main/MainContent.jsx
  src/components/main/MeetingSlider.jsx
  src/components/meeting/MeetingCalendar.jsx
  src/components/my/Avatar.jsx
  src/components/my/NicknameForm.jsx
  src/components/user/RegistForm.jsx
  src/hooks/useBoardQuery.js
  src/hooks/useCommentQuery.js
  src/hooks/useMeetingQuery.js
Labels: refactor, style

#150 폰트 사이즈 통일
  src/components/auth/KakaoLogin.jsx
  src/components/auth/KakaoRedirect.jsx
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/Pagination.jsx
  src/components/comment/CommentWriter.jsx
  src/components/common/StyledButton.jsx
  src/components/main/MainContent.jsx
  src/components/user/LoginForm.jsx
  src/components/user/UserModal.jsx
Labels: style

#152 위치 정보 훅 리팩토링
  src/components/meeting/MeetingCalendar.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingNav.jsx
  src/hooks/useCurrentLocation.js
  src/hooks/useMeetingQuery.js
Labels: refactor, style

#153 위치정보 로딩 애니메이션 추가
  src/components/auth/Spinner.jsx
  src/components/meeting/MeetingNav.jsx
Labels: style

#157 카카오 맵 위치 정보 리팩토링
  src/components/meeting/MeetingMap.jsx
  src/components/meeting/MeetingNav.jsx
  src/hooks/useCurrentLocation.js
Labels: refactor

#156 좋아요 버튼 예외처리
  src/components/board/LikeBtn.jsx
  src/components/common/AlarmModal.jsx
Labels: feature

#158 모임 네비게이션, 모임 인원 컴포넌트 리팩토링
  src/components/meeting/MeetingNav.jsx
  src/components/meeting/MemberCounter.jsx
  src/hooks/useCurrentLocation.js
Labels: refactor

#159 위치 서비스 로직 리팩토링
  src/components/meeting/MeetingNav.jsx
  src/hooks/useCurrentLocation.js
Labels: refactor

#162 모임 지도 관심사 별 로직 분리
  src/components/meeting/MeetingMap.jsx
  src/hooks/useCurrentLocation.js
Labels: refactor

#163 게시물 상세 페이지 리팩토링
  src/components/board/BoardAction.jsx
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/DeleteBoardAlarm.jsx
  src/components/board/LikeBtn.jsx
  src/components/comment/CommentList.jsx
  src/components/common/AlarmModal.jsx
  src/components/common/Header.jsx
  src/components/user/LoginForm.jsx
  src/pages/BoardDetailPage.jsx
Labels: refactor

#164 모임 지도 뒷정리 함수 추가
  src/components/meeting/MeetingMap.jsx
  src/components/meeting/MeetingNav.jsx
  src/hooks/useCurrentLocation.js
Labels: refactor

#165 게시물 상세페이지 리팩토링
  src/components/board/BoardAction.jsx
  src/components/board/BoardViewer.jsx
  src/components/board/LikeBtn.jsx
  src/components/common/AlarmModal.jsx
  src/components/common/Header.jsx
Labels: refactor

#167 모임 생성 시 예외 처리 구현
  src/components/meeting/MeetingWriteButton.jsx
  src/hooks/useError.js
Labels: feature

#168 알람 공통 컴포넌트 구현
  src/components/common/AlarmContent.jsx
  src/components/common/AlarmModal.jsx
  src/components/common/ModalOverlay.jsx
  src/components/meeting/MeetingDetail.jsx
  src/components/meeting/MeetingWriteButton.jsx
  src/components/user/UserModal.jsx
Labels: feature

#170 메인 페이지 반응형 레이아웃 수정
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/main/Banner.jsx
  src/components/main/MainContent.jsx
  src/components/main/MeetingSlider.jsx
Labels: style

#172 게시물 상세페이지 모임 상세페이지 정보 레이아웃 수정
  src/components/board/BoardAction.jsx
  src/components/board/BoardDetail.jsx
  src/components/board/BoardEditor.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardSubInfo.jsx
  src/components/board/BoardViewer.jsx
  src/components/board/DateInfo.jsx
  src/components/board/DeleteBoardAlarm.jsx
  src/components/board/LikeBtn.jsx
  src/components/comment/CommentItem.jsx
  src/components/comment/CommentList.jsx
  src/components/meeting/MeetingDetail.jsx
Labels: style

#174 모임 슬라이더 스타일 수정
  src/components/main/MeetingSlider.jsx
  src/components/meeting/MeetingItem.jsx
Labels: style

#176 스타일 수정
  src/components/board/BoardDetail.jsx
  src/components/board/BoardItem.jsx
  src/components/board/BoardNav.jsx
  src/components/common/Header.jsx
  src/components/common/StyledButton.jsx
  src/styles/GlobalStyles.jsx
Labels: style

#177 설정 파일 수정
  package.json
  public/index.html
Labels: config

#179 빌드 명령어 수정
  README.md
  package.json
Labels: config

#180 메인 브랜치로 병합
  README.md
  package.json
Labels: config

#181 버튼, 링크 기본 스타일 리셋 코드 이동
  src/components/meeting/MeetingNav.jsx
  src/styles/GlobalStyles.jsx
Labels: style

#182 변경 사항 메인 브랜치로 병합
  src/components/meeting/MeetingNav.jsx
  src/styles/GlobalStyles.jsx
Labels: style

#183 헤더 UI 수정, 불필요 코드 제거
  src/components/board/BoardList.jsx
  src/components/common/Header.jsx
Labels: refactor, style

#184 변경사항 메인 브렌치로 병합
  src/components/board/BoardList.jsx
  src/components/common/Header.jsx
Labels: refactor, style

#185 게시물 리스트 페이지 UI 수정
  src/components/board/BoardNav.jsx
Labels: style

#186 변경사항 메인 브렌치로 병합
  src/components/board/BoardNav.jsx
Labels: style

#188 netlify 리다이렉트 설정
  netlify.toml
  public/_redirects
Labels: config
